version: '3.8'
services:
  frontend:
    build:
      context: ./atx-happy-hour-map
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"